### ISSUE TITLE
clojure-logo icon prevents uberjar from running

### ISSUE THREAD

**Issue by jbwyatt4** [vascoferreira25/seesaw-gui-application#1]
Hello,

I am new to Clojure and I was looking for a good example of a working uberjar.

Your program worked with the uberjar option after commenting out line 76: the set icon. I believe the icon is not being included in the uberjar. What option would you add to include the icon?

**Comment by vascoferreira25** [comment]
> 
> 
> Hello,
> 
> I am new to Clojure and I was looking for a good example of a working uberjar.
> 
> Your program worked with the uberjar option after commenting out line 76: the set icon. I believe the icon is not being included in the uberjar. What option would you add to include the icon?

Hello, thank you for trying this simple program. I've done the same as you did and it doesn't work because of path of png image.

To make it work, you just need to change the path from `./clojure-logo-120b.png` to `clojure-logo-120b.png`. I will fix this in the source code.
